version: '3.3'

services:
  lita:
    build:
      context: .
      args:
        ARG_VERSION_MAJOR: ${VERSION_MAJOR}
        ARG_VERSION_MINOR: ${VERSION_MINOR}
        ARG_VERSION_PATCH: ${VERSION_PATCH}
        ARG_RELEASE: ${RELEASE}
        ARG_NAME_COLUMN: ${NAME_COLUMN}
        ARG_TIME_COLUMN: ${TIME_COLUMN}
        ARG_VALUE_COLUMN: ${VALUE_COLUMN}
        ARG_DISPLAY: host.docker.internal:0
        ARG_RAVEN_SECRET_KEY: ${RAVEN_SECRET_KEY}
    restart: always
    volumes:
      - type: bind
        source: ${TELEMETRY_ARCHIVE}
        target: /srv/telemetry/archive/
      - type: bind
        source: ${STAGING_DIRECTORY}
        target: /srv/telemetry/staging/
      - type: bind
        source: ${JUPYTERHUB_CONFIG_DIRECTORY}
        target: /srv/jupyterhub/config/
      - type: bind
        source: ${JUPYTERHUB_LOG_DIRECTORY}
        target: /srv/jeta/log/
      - type: bind
        source: ${JUPYTERHUB_USER_SPACE}
        target: /home
    ports:
      - "9232:9232"
      - "5050:5050"
      - "9300:9300"
    environment:
      - "WORKERS=${WORKERS}"
networks:
  default:
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}